// Standard country list for the contact form's Country field, with
// accurate English/German/French names. The three target markets (USA,
// Germany, Austria) are pinned first by the caller; everything else is
// alphabetized in the visitor's own locale at render time, not here.
import type { Locale } from "@/i18n/config";

export interface CountryName {
  en: string;
  de: string;
  fr: string;
}

export const PRIORITY_COUNTRIES: CountryName[] = [
  { en: "United States", de: "Vereinigte Staaten", fr: "États-Unis" },
  { en: "Germany", de: "Deutschland", fr: "Allemagne" },
  { en: "Austria", de: "Österreich", fr: "Autriche" },
];

export const OTHER_COUNTRIES: CountryName[] = [
  { en: "Afghanistan", de: "Afghanistan", fr: "Afghanistan" },
  { en: "Albania", de: "Albanien", fr: "Albanie" },
  { en: "Algeria", de: "Algerien", fr: "Algérie" },
  { en: "Andorra", de: "Andorra", fr: "Andorre" },
  { en: "Angola", de: "Angola", fr: "Angola" },
  { en: "Argentina", de: "Argentinien", fr: "Argentine" },
  { en: "Armenia", de: "Armenien", fr: "Arménie" },
  { en: "Australia", de: "Australien", fr: "Australie" },
  { en: "Azerbaijan", de: "Aserbaidschan", fr: "Azerbaïdjan" },
  { en: "Bahamas", de: "Bahamas", fr: "Bahamas" },
  { en: "Bahrain", de: "Bahrain", fr: "Bahreïn" },
  { en: "Bangladesh", de: "Bangladesch", fr: "Bangladesh" },
  { en: "Barbados", de: "Barbados", fr: "Barbade" },
  { en: "Belarus", de: "Belarus", fr: "Biélorussie" },
  { en: "Belgium", de: "Belgien", fr: "Belgique" },
  { en: "Belize", de: "Belize", fr: "Belize" },
  { en: "Benin", de: "Benin", fr: "Bénin" },
  { en: "Bhutan", de: "Bhutan", fr: "Bhoutan" },
  { en: "Bolivia", de: "Bolivien", fr: "Bolivie" },
  { en: "Bosnia and Herzegovina", de: "Bosnien und Herzegowina", fr: "Bosnie-Herzégovine" },
  { en: "Botswana", de: "Botswana", fr: "Botswana" },
  { en: "Brazil", de: "Brasilien", fr: "Brésil" },
  { en: "Brunei", de: "Brunei", fr: "Brunei" },
  { en: "Bulgaria", de: "Bulgarien", fr: "Bulgarie" },
  { en: "Burkina Faso", de: "Burkina Faso", fr: "Burkina Faso" },
  { en: "Burundi", de: "Burundi", fr: "Burundi" },
  { en: "Cambodia", de: "Kambodscha", fr: "Cambodge" },
  { en: "Cameroon", de: "Kamerun", fr: "Cameroun" },
  { en: "Canada", de: "Kanada", fr: "Canada" },
  { en: "Cape Verde", de: "Kap Verde", fr: "Cap-Vert" },
  { en: "Central African Republic", de: "Zentralafrikanische Republik", fr: "République centrafricaine" },
  { en: "Chad", de: "Tschad", fr: "Tchad" },
  { en: "Chile", de: "Chile", fr: "Chili" },
  { en: "China", de: "China", fr: "Chine" },
  { en: "Colombia", de: "Kolumbien", fr: "Colombie" },
  { en: "Comoros", de: "Komoren", fr: "Comores" },
  { en: "Costa Rica", de: "Costa Rica", fr: "Costa Rica" },
  { en: "Croatia", de: "Kroatien", fr: "Croatie" },
  { en: "Cuba", de: "Kuba", fr: "Cuba" },
  { en: "Cyprus", de: "Zypern", fr: "Chypre" },
  { en: "Czech Republic", de: "Tschechien", fr: "République tchèque" },
  { en: "Democratic Republic of the Congo", de: "Demokratische Republik Kongo", fr: "République démocratique du Congo" },
  { en: "Denmark", de: "Dänemark", fr: "Danemark" },
  { en: "Djibouti", de: "Dschibuti", fr: "Djibouti" },
  { en: "Dominica", de: "Dominica", fr: "Dominique" },
  { en: "Dominican Republic", de: "Dominikanische Republik", fr: "République dominicaine" },
  { en: "Ecuador", de: "Ecuador", fr: "Équateur" },
  { en: "Egypt", de: "Ägypten", fr: "Égypte" },
  { en: "El Salvador", de: "El Salvador", fr: "Salvador" },
  { en: "Equatorial Guinea", de: "Äquatorialguinea", fr: "Guinée équatoriale" },
  { en: "Eritrea", de: "Eritrea", fr: "Érythrée" },
  { en: "Estonia", de: "Estland", fr: "Estonie" },
  { en: "Eswatini", de: "Eswatini", fr: "Eswatini" },
  { en: "Ethiopia", de: "Äthiopien", fr: "Éthiopie" },
  { en: "Fiji", de: "Fidschi", fr: "Fidji" },
  { en: "Finland", de: "Finnland", fr: "Finlande" },
  { en: "France", de: "Frankreich", fr: "France" },
  { en: "Gabon", de: "Gabun", fr: "Gabon" },
  { en: "Gambia", de: "Gambia", fr: "Gambie" },
  { en: "Georgia", de: "Georgien", fr: "Géorgie" },
  { en: "Ghana", de: "Ghana", fr: "Ghana" },
  { en: "Greece", de: "Griechenland", fr: "Grèce" },
  { en: "Grenada", de: "Grenada", fr: "Grenade" },
  { en: "Guatemala", de: "Guatemala", fr: "Guatemala" },
  { en: "Guinea", de: "Guinea", fr: "Guinée" },
  { en: "Guinea-Bissau", de: "Guinea-Bissau", fr: "Guinée-Bissau" },
  { en: "Guyana", de: "Guyana", fr: "Guyana" },
  { en: "Haiti", de: "Haiti", fr: "Haïti" },
  { en: "Honduras", de: "Honduras", fr: "Honduras" },
  { en: "Hungary", de: "Ungarn", fr: "Hongrie" },
  { en: "Iceland", de: "Island", fr: "Islande" },
  { en: "India", de: "Indien", fr: "Inde" },
  { en: "Indonesia", de: "Indonesien", fr: "Indonésie" },
  { en: "Iran", de: "Iran", fr: "Iran" },
  { en: "Iraq", de: "Irak", fr: "Irak" },
  { en: "Ireland", de: "Irland", fr: "Irlande" },
  { en: "Israel", de: "Israel", fr: "Israël" },
  { en: "Italy", de: "Italien", fr: "Italie" },
  { en: "Ivory Coast", de: "Elfenbeinküste", fr: "Côte d'Ivoire" },
  { en: "Jamaica", de: "Jamaika", fr: "Jamaïque" },
  { en: "Japan", de: "Japan", fr: "Japon" },
  { en: "Jordan", de: "Jordanien", fr: "Jordanie" },
  { en: "Kazakhstan", de: "Kasachstan", fr: "Kazakhstan" },
  { en: "Kenya", de: "Kenia", fr: "Kenya" },
  { en: "Kiribati", de: "Kiribati", fr: "Kiribati" },
  { en: "Kosovo", de: "Kosovo", fr: "Kosovo" },
  { en: "Kuwait", de: "Kuwait", fr: "Koweït" },
  { en: "Kyrgyzstan", de: "Kirgisistan", fr: "Kirghizistan" },
  { en: "Laos", de: "Laos", fr: "Laos" },
  { en: "Latvia", de: "Lettland", fr: "Lettonie" },
  { en: "Lebanon", de: "Libanon", fr: "Liban" },
  { en: "Lesotho", de: "Lesotho", fr: "Lesotho" },
  { en: "Liberia", de: "Liberia", fr: "Libéria" },
  { en: "Libya", de: "Libyen", fr: "Libye" },
  { en: "Liechtenstein", de: "Liechtenstein", fr: "Liechtenstein" },
  { en: "Lithuania", de: "Litauen", fr: "Lituanie" },
  { en: "Luxembourg", de: "Luxemburg", fr: "Luxembourg" },
  { en: "Madagascar", de: "Madagaskar", fr: "Madagascar" },
  { en: "Malawi", de: "Malawi", fr: "Malawi" },
  { en: "Malaysia", de: "Malaysia", fr: "Malaisie" },
  { en: "Maldives", de: "Malediven", fr: "Maldives" },
  { en: "Mali", de: "Mali", fr: "Mali" },
  { en: "Malta", de: "Malta", fr: "Malte" },
  { en: "Mauritania", de: "Mauretanien", fr: "Mauritanie" },
  { en: "Mauritius", de: "Mauritius", fr: "Maurice" },
  { en: "Mexico", de: "Mexiko", fr: "Mexique" },
  { en: "Moldova", de: "Moldau", fr: "Moldavie" },
  { en: "Monaco", de: "Monaco", fr: "Monaco" },
  { en: "Mongolia", de: "Mongolei", fr: "Mongolie" },
  { en: "Montenegro", de: "Montenegro", fr: "Monténégro" },
  { en: "Morocco", de: "Marokko", fr: "Maroc" },
  { en: "Mozambique", de: "Mosambik", fr: "Mozambique" },
  { en: "Myanmar", de: "Myanmar", fr: "Birmanie" },
  { en: "Namibia", de: "Namibia", fr: "Namibie" },
  { en: "Nauru", de: "Nauru", fr: "Nauru" },
  { en: "Nepal", de: "Nepal", fr: "Népal" },
  { en: "Netherlands", de: "Niederlande", fr: "Pays-Bas" },
  { en: "New Zealand", de: "Neuseeland", fr: "Nouvelle-Zélande" },
  { en: "Nicaragua", de: "Nicaragua", fr: "Nicaragua" },
  { en: "Niger", de: "Niger", fr: "Niger" },
  { en: "Nigeria", de: "Nigeria", fr: "Nigeria" },
  { en: "North Korea", de: "Nordkorea", fr: "Corée du Nord" },
  { en: "North Macedonia", de: "Nordmazedonien", fr: "Macédoine du Nord" },
  { en: "Norway", de: "Norwegen", fr: "Norvège" },
  { en: "Oman", de: "Oman", fr: "Oman" },
  { en: "Pakistan", de: "Pakistan", fr: "Pakistan" },
  { en: "Palau", de: "Palau", fr: "Palaos" },
  { en: "Palestine", de: "Palästina", fr: "Palestine" },
  { en: "Panama", de: "Panama", fr: "Panama" },
  { en: "Papua New Guinea", de: "Papua-Neuguinea", fr: "Papouasie-Nouvelle-Guinée" },
  { en: "Paraguay", de: "Paraguay", fr: "Paraguay" },
  { en: "Peru", de: "Peru", fr: "Pérou" },
  { en: "Philippines", de: "Philippinen", fr: "Philippines" },
  { en: "Poland", de: "Polen", fr: "Pologne" },
  { en: "Portugal", de: "Portugal", fr: "Portugal" },
  { en: "Qatar", de: "Katar", fr: "Qatar" },
  { en: "Republic of the Congo", de: "Republik Kongo", fr: "République du Congo" },
  { en: "Romania", de: "Rumänien", fr: "Roumanie" },
  { en: "Russia", de: "Russland", fr: "Russie" },
  { en: "Rwanda", de: "Ruanda", fr: "Rwanda" },
  { en: "Saint Lucia", de: "St. Lucia", fr: "Sainte-Lucie" },
  { en: "Samoa", de: "Samoa", fr: "Samoa" },
  { en: "San Marino", de: "San Marino", fr: "Saint-Marin" },
  { en: "Saudi Arabia", de: "Saudi-Arabien", fr: "Arabie saoudite" },
  { en: "Senegal", de: "Senegal", fr: "Sénégal" },
  { en: "Serbia", de: "Serbien", fr: "Serbie" },
  { en: "Seychelles", de: "Seychellen", fr: "Seychelles" },
  { en: "Sierra Leone", de: "Sierra Leone", fr: "Sierra Leone" },
  { en: "Singapore", de: "Singapur", fr: "Singapour" },
  { en: "Slovakia", de: "Slowakei", fr: "Slovaquie" },
  { en: "Slovenia", de: "Slowenien", fr: "Slovénie" },
  { en: "Solomon Islands", de: "Salomonen", fr: "Îles Salomon" },
  { en: "Somalia", de: "Somalia", fr: "Somalie" },
  { en: "South Africa", de: "Südafrika", fr: "Afrique du Sud" },
  { en: "South Korea", de: "Südkorea", fr: "Corée du Sud" },
  { en: "South Sudan", de: "Südsudan", fr: "Soudan du Sud" },
  { en: "Spain", de: "Spanien", fr: "Espagne" },
  { en: "Sri Lanka", de: "Sri Lanka", fr: "Sri Lanka" },
  { en: "Sudan", de: "Sudan", fr: "Soudan" },
  { en: "Suriname", de: "Suriname", fr: "Suriname" },
  { en: "Sweden", de: "Schweden", fr: "Suède" },
  { en: "Switzerland", de: "Schweiz", fr: "Suisse" },
  { en: "Syria", de: "Syrien", fr: "Syrie" },
  { en: "Taiwan", de: "Taiwan", fr: "Taïwan" },
  { en: "Tajikistan", de: "Tadschikistan", fr: "Tadjikistan" },
  { en: "Tanzania", de: "Tansania", fr: "Tanzanie" },
  { en: "Thailand", de: "Thailand", fr: "Thaïlande" },
  { en: "Togo", de: "Togo", fr: "Togo" },
  { en: "Tonga", de: "Tonga", fr: "Tonga" },
  { en: "Trinidad and Tobago", de: "Trinidad und Tobago", fr: "Trinité-et-Tobago" },
  { en: "Tunisia", de: "Tunesien", fr: "Tunisie" },
  { en: "Turkey", de: "Türkei", fr: "Turquie" },
  { en: "Turkmenistan", de: "Turkmenistan", fr: "Turkménistan" },
  { en: "Uganda", de: "Uganda", fr: "Ouganda" },
  { en: "Ukraine", de: "Ukraine", fr: "Ukraine" },
  { en: "United Arab Emirates", de: "Vereinigte Arabische Emirate", fr: "Émirats arabes unis" },
  { en: "United Kingdom", de: "Vereinigtes Königreich", fr: "Royaume-Uni" },
  { en: "Uruguay", de: "Uruguay", fr: "Uruguay" },
  { en: "Uzbekistan", de: "Usbekistan", fr: "Ouzbékistan" },
  { en: "Vanuatu", de: "Vanuatu", fr: "Vanuatu" },
  { en: "Vatican City", de: "Vatikanstadt", fr: "Vatican" },
  { en: "Venezuela", de: "Venezuela", fr: "Venezuela" },
  { en: "Vietnam", de: "Vietnam", fr: "Vietnam" },
  { en: "Yemen", de: "Jemen", fr: "Yémen" },
  { en: "Zambia", de: "Sambia", fr: "Zambie" },
  { en: "Zimbabwe", de: "Simbabwe", fr: "Zimbabwe" },
];

/** Priority countries first (in the visitor's locale), then the rest
 * alphabetized in that same locale, then a final catch-all option. */
export function getCountryOptions(locale: Locale, otherLabel: string): string[] {
  const rest = [...OTHER_COUNTRIES]
    .map((c) => c[locale])
    .sort((a, b) => a.localeCompare(b, locale));
  return [...PRIORITY_COUNTRIES.map((c) => c[locale]), ...rest, otherLabel];
}
